-- Généré depuis assets/js/config.js — ne pas éditer à la main.
DELETE FROM settings; DELETE FROM categories; DELETE FROM produits; DELETE FROM livraison_zones; DELETE FROM faq; DELETE FROM avis;
INSERT INTO settings (key,value) VALUES ('boutique','{"nom":"Nolimit Shop","slogan":"La mode sans limite, livrée chez toi","description":"Chemises & polos oversize — Dakar, Sénégal","whatsapp":"221770321603","whatsappLien":"https://wa.me/message/Z65TGEO5YBMUD1","telephone":"","email":"","adresse":"Dakar, Sénégal","horaires":"","instagram":"https://www.instagram.com/no_limite_shop221","tiktok":"https://www.tiktok.com/@nolimiteshop3","snapchat":"https://snapchat.com/t/cJXjTP5j","facebook":""}');
INSERT INTO settings (key,value) VALUES ('gratuite_apartir','0');
INSERT INTO settings (key,value) VALUES ('admin_password','nolimit2026');
INSERT INTO categories (id,nom,emoji,ordre) VALUES ('chemises','Chemises','👕',0);
INSERT INTO categories (id,nom,emoji,ordre) VALUES ('polos','Polos','👔',1);
INSERT INTO produits (id,nom,sous_titre,categorie,prix,prix_barre,stock,vedette,badge,description,tailles,couleurs,details,images,ordre) VALUES ('chemise-saved-by-jesus','Chemise Saved By Jesus','Coupe oversize, carreaux noir & blanc','chemises',18000,0,1,1,'Nouveau','Chemise à manches courtes coupe oversize, tissu à carreaux noir et blanc, gros lettrage jaune « SAVED BY JESUS » sur le devant. Une pièce forte qui se porte ouverte sur un t-shirt ou fermée.','["M","L","XL","XXL"]','["Noir / Blanc"]','["Coupe oversize (boxy)","Manches courtes, col chemise","Impression jaune effet vintage","Tissu léger, agréable par forte chaleur"]','["assets/img/chemise-saved-by-jesus-1.jpg"]',0);
INSERT INTO produits (id,nom,sous_titre,categorie,prix,prix_barre,stock,vedette,badge,description,tailles,couleurs,details,images,ordre) VALUES ('chemise-desert-tour','Chemise Desert Tour brodée','Broderie intégrale, boutons pression','chemises',32000,0,1,1,'Pièce rare','Chemise oversize entièrement brodée : paysage désert, cactus et ciel orangé, empiècements turquoise et rouge. Fermeture à boutons pression. Une pièce statement, aucune autre ne lui ressemble.','["M","L","XL"]','["Multicolore"]','["Broderie sur toute la surface","Boutons pression métal","Coupe oversize courte","Intérieur doublé"]','["assets/img/chemise-desert-tour-1.jpg"]',1);
INSERT INTO produits (id,nom,sous_titre,categorie,prix,prix_barre,stock,vedette,badge,description,tailles,couleurs,details,images,ordre) VALUES ('chemise-corteiz-rose','Chemise rayée Corteiz','Rayures rose & noir, logo floqué','chemises',20000,25000,1,1,'Promo','Chemise oversize à rayures rose et noir avec gros logo Corteiz floqué au centre et petit logo en bas. Poche poitrine. Le streetwear qui se remarque.','["M","L","XL","XXL"]','["Rose / Noir"]','["Coupe oversize (boxy)","Poche poitrine","Logo floqué effet relief","Tissu fluide"]','["assets/img/chemise-corteiz-rose-1.jpg"]',2);
INSERT INTO produits (id,nom,sous_titre,categorie,prix,prix_barre,stock,vedette,badge,description,tailles,couleurs,details,images,ordre) VALUES ('polo-risky-argyle','Polo Risky Private Club','Maille argyle bordeaux, beige & blanc','polos',22000,0,1,1,'Nouveau','Polo en maille motif argyle (losanges) bordeaux, beige et blanc, avec broderie « Risky Private Club » et écusson drapeau. Col et poignets contrastés. Chic et décontracté à la fois.','["M","L","XL"]','["Bordeaux / Beige"]','["Maille jacquard motif argyle","Broderies et écusson appliqué","Col et poignets en velours côtelé","Fermeture 3 boutons pression"]','["assets/img/polo-risky-argyle-1.jpg"]',3);
INSERT INTO faq (q,r,ordre) VALUES ('Comment passer commande ?','Ajoutez vos articles au panier, cliquez sur « Commander », remplissez vos coordonnées : votre commande part directement sur notre WhatsApp. On vous recontacte ensuite pour confirmer les détails (livraison, paiement).',0);
INSERT INTO faq (q,r,ordre) VALUES ('Comment choisir ma taille ?','Chaque fiche produit indique les tailles disponibles. En cas de doute, écrivez-nous sur WhatsApp avec votre taille habituelle, nous vous conseillons.',1);
